projects:
  default:
    schema: "../gpngen2/massagex-backend/src/models/schema.graphql"
    documents: 
      - '../gpngen2/massagex-backend/src/schemas/**/*.graphql'
      - '../gpngen2/massagex-backend/src/app-schemas/**/*.graphql'
    exclude: '!../gpngen2/massagex-backend/src/authorization/policy/*.graphql'
    extensions:
      endpoints:
        default:
          url: http://localhost:3000/graphql
          headers:
            authorization: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InRCME0yQSJ9.eyJpc3MiOiJodHRwczovL3Nlc3Npb24uZmlyZWJhc2UuZ29vZ2xlLmNvbS9mYXctaWRlbnRpZmljYXRpb24iLCJuYW1lIjoiQ29vbCB1c2VyIiwicm9sZSI6IlVTRVIiLCJhdWQiOiJmYXctaWRlbnRpZmljYXRpb24iLCJhdXRoX3RpbWUiOjE2MDMwMDE5NzgsInVzZXJfaWQiOiJGV2VDdWpscm5FYjJ1cWFwTGM5S24wRXhSTm0yIiwic3ViIjoiRldlQ3VqbHJuRWIydXFhcExjOUtuMEV4Uk5tMiIsImlhdCI6MTYwMzAwMTk4MywiZXhwIjoxNjAzNDMzOTgzLCJlbWFpbCI6InVzZXIxQGV4YW1wbGUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInVzZXIxQGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Qx8OR_nRSgegqaU7xg6TMvX_BEcqLUfuenOYwe8yjLDtASw6yPWv00v1oWGh3HJgycIeZG39ppNgDFhVx4Ts7n2lwZWzPtCKLB_mjCGxyPlUJAD7ZRwTr0l7DhX2hujKlCC_RIqQjtr8G00APVJvGZlbB3WTqYLwDmfSlu30zVXZdXNUh3n8Y6o83ua1cczLFxX7ZFORd2KCeW55AmhX_qemGtruHqDne-XAaGr6UTZNO-u2Ctdr0gSlLtL3x9RAUxEJXiwouSD5MMUIKv2Lq-di3DTb5CTrQMTXJMuFE0nSs2_4cFyuw759O__CrBYFIBUU8qAq8wcZk1I7VSZsoQ"
  policy:
    schema: "../gpngen2/massagex-backend/src/authorization/policy/policy.graphql"
    documents: "../gpngen2/massagex-backend/src/authorization/policy/*.graphql"
