#!/bin/bash
./scripts/tobase64 .env
./scripts/tobase64  serviceAccount.json
./scripts/tobase64  prisma/.env
./scripts/tobase64  webserver/nginx-conf/nginx.conf
./scripts/tobase64  webserver/certbot/nginx-conf/nginx.conf


